CREATE TABLE room (id TEXT PRIMARY KEY, name TEXT NOT NULL, owner_person_id TEXT, bar INTEGER NOT NULL DEFAULT 50, created_at TEXT NOT NULL);
CREATE TABLE person (id TEXT PRIMARY KEY, room_id TEXT NOT NULL, display_name TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, groups TEXT NOT NULL DEFAULT '[]', kid_ages TEXT, default_view TEXT NOT NULL DEFAULT 'odd', visibility TEXT NOT NULL DEFAULT 'mutual', removed_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE place (id TEXT PRIMARY KEY, name TEXT NOT NULL, address TEXT, lat REAL, lng REAL, neighborhood TEXT, groups TEXT NOT NULL DEFAULT '[]', canonical_key TEXT NOT NULL UNIQUE, geocode_source TEXT, geocoded_at TEXT, created_by TEXT NOT NULL, merged_into TEXT, created_at TEXT NOT NULL);
CREATE TABLE event (id TEXT PRIMARY KEY, place_id TEXT NOT NULL, title TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT, groups TEXT NOT NULL DEFAULT '[]', answers TEXT NOT NULL DEFAULT '{}', score INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'live', reject_reason TEXT, dedupe_key TEXT NOT NULL UNIQUE, raw TEXT NOT NULL DEFAULT '{}', first_seen TEXT NOT NULL, last_seen TEXT NOT NULL);
CREATE TABLE event_source (event_id TEXT NOT NULL, source TEXT NOT NULL, source_id TEXT NOT NULL, source_url TEXT, seen_at TEXT NOT NULL, PRIMARY KEY (source, source_id));
CREATE TABLE vouch (place_id TEXT NOT NULL, person_id TEXT NOT NULL, line TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (place_id, person_id));
CREATE TABLE review (id TEXT PRIMARY KEY, place_id TEXT NOT NULL, person_id TEXT NOT NULL, visited_on TEXT, verdict TEXT NOT NULL, text TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE interest (person_id TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, created_at TEXT NOT NULL, refreshed_at TEXT NOT NULL, PRIMARY KEY (person_id, target_type, target_id));
CREATE TABLE tick (from_person_id TEXT NOT NULL, to_person_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (from_person_id, to_person_id));
CREATE TABLE availability (id TEXT PRIMARY KEY, person_id TEXT NOT NULL, kind TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, note TEXT);
CREATE TABLE plan (id TEXT PRIMARY KEY, room_id TEXT NOT NULL, owner_person_id TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, starts_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL, done_at TEXT);
CREATE TABLE plan_member (plan_id TEXT NOT NULL, person_id TEXT NOT NULL, state TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (plan_id, person_id));
CREATE TABLE mute (room_id TEXT NOT NULL, category TEXT NOT NULL, PRIMARY KEY (room_id, category));
CREATE TABLE prompt_seen (person_id TEXT NOT NULL, place_id TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (person_id, place_id));
CREATE INDEX idx_event_starts ON event (status, starts_at);
CREATE INDEX idx_event_place ON event (place_id);
CREATE INDEX idx_interest_target ON interest (target_type, target_id);
CREATE INDEX idx_tick_to ON tick (to_person_id);
CREATE INDEX idx_availability_person ON availability (person_id, start_date);
CREATE INDEX idx_plan_member_person ON plan_member (person_id);
CREATE INDEX idx_review_place ON review (place_id);
CREATE INDEX idx_review_person ON review (person_id);
